# Generated by Django 4.1.1 on 2022-09-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FirstApp',
            new_name='First_table',
        ),
    ]
